#!/usr/bin/env python3

# Copyright (c) 2000-2025, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Remove in Python 3.14
# See https://stackoverflow.com/questions/33533148/how-do-i-type-hint-a-method-with-the-type-of-the-enclosing-class/33533514#33533514
from __future__ import annotations

from collections.abc import Callable, Iterable
from dataclasses import dataclass
import json
import jsonpath
from pprint import pformat
import sys
from typing import Any, ClassVar, Optional, Union
import warnings
import yaml
from click import Choice

from click_extra import Choice, ChoiceSource, EnumChoice, TableFormat, echo, option, option_group, table_format_option
from cloup.constraints import AnySet, If, Not, accept_none, mutually_exclusive
from pygments import highlight
from pygments.formatters.terminal256 import Terminal256Formatter
from pygments.lexers.data import JsonLexer, YamlLexer
from pygments.lexers.python import PythonLexer

from lockss.pybasic.cliutil import NonNegativeInt, compose_decorators
from lockss.pybasic.errorutil import InternalError

'''
from lockss.pybasic.cliutil import at_most_one
from lockss.pybasic.outpututil import OutputFormat
from pydantic.v1 import BaseModel as BaseModel1, PositiveInt as PositiveInt1, create_model as create_model1, root_validator as root_validator1, validator as validator1
from pydantic.v1.fields import Field as Field1, FieldInfo as FieldInfo1, PrivateAttr as PrivateAttr1
import tabulate
'''

#: The objects generated by Swagger-Codegen
SwaggerObject = object


'''
class BaseOutputOptions(BaseModel1):
    DEFAULT_INDENT: ClassVar[PositiveInt1] = 4
    DEFAULT_TABULAR: ClassVar[str] = 'tsv'

    x_json: Optional[bool] = Field1(False, alias='json', aliases=['-j'], description='(output style) output the result as JSON') # 'json' is a BaseModel name
    jsonpath: Optional[str] = Field1(aliases=['-J'], description='(output style) output the result after applying the given JSONPath')
    tabular: Optional[bool] = Field1(False, aliases=['-t'], description='(output style) output the result in tabular form')
    yaml: Optional[bool] = Field1(False, aliases=['-y'], description='(output style) output the result as YAML')
    indent: Optional[PositiveInt1] = Field1(DEFAULT_INDENT, description='(JSON/YAML output) indentation spaces')
    tabular_format: Optional[str] = Field1(DEFAULT_TABULAR, aliases=['-T'], description=f'(tabular output) output the result in the given tabular format; choices: {', '.join(OutputFormat.__members__)}')

    @root_validator1
    def _validate_output_type(cls: type[BaseOutputOptions], values: dict[str, Any]) -> dict[str, Any]:
        return at_most_one(cls, values, 'x_json', 'jsonpath', 'tabular', 'yaml')

    @validator1('tabular_format')
    def _validate_tabular(cls: type[BaseOutputOptions], v: Optional[str]) -> Optional[str]:
        if v and v not in OutputFormat.__members__:
            raise ValueError(f'exactly one of {', '.join(OutputFormat.__members__)} required; got {v}')
        return v

    def display(self,
                iterable_or_obj: Union[Iterable[SwaggerObject], SwaggerObject],
                file: Any=sys.stdout) -> None:
        iterable = iterable_or_obj if isinstance(iterable_or_obj, Iterable) else [iterable_or_obj]
        if self.x_json:
            self.display_json(iterable, file=file)
        elif self.jsonpath:
            self.display_jsonpath(iterable, file=file)
        elif self.tabular:
            self.display_tabular(iterable, file=file)
        elif self.yaml:
            self.display_yaml(iterable, file=file)
        else:
            for obj in iterable:
                print(obj.to_dict())

    def display_json(self, iterable: Iterable[SwaggerObject], file: Any) -> None:
        for obj in iterable:
            print(json.dumps(obj.to_dict(), indent=self.indent), file=file)

    def display_jsonpath(self, iterable: Iterable[SwaggerObject], file: Any) -> None:
        for obj in iterable:
            print(jsonpath.findall(self.jsonpath, obj.to_dict()), file=file)

    def display_tabular(self, iterable: Iterable[SwaggerObject], file: Any) -> None:
        attrs = [attr.removeprefix('include_') if model.field_info.extra.get('disambiguated') else attr for attr, model in self.__fields__.items() if model.field_info.extra.get('column') and getattr(self, attr)] \
                or [attr.removeprefix('include_') if model.field_info.extra.get('disambiguated') else attr for attr, model in self.__fields__.items() if model.field_info.extra.get('column')]
        headers = [] if self.no_headers else [self._target_cls.attribute_map[attr] for attr in attrs]
        data = [[str(getattr(obj, attr)) for attr in attrs] for obj in iterable]
        print(tabulate.tabulate(data, headers=headers, tablefmt=self.tabular_format), file=file)

    def display_yaml(self, iterable: Iterable[SwaggerObject], file: Any) -> None:
        for obj in iterable:
            print(yaml.dump(obj.to_dict(), indent=self.indent), file=file)


def output_options(type_name: str,
                   target_cls: type[SwaggerObject],
                   disambiguate: Optional[list[str]] = None):
    disambiguate = disambiguate or []
    with warnings.catch_warnings():
        warnings.simplefilter("ignore") # Pydantic v1 demands that PrivateAttr begins with a hyphen but warns that _target_cls begins with a hyphen
        return create_model1(type_name,
                             __base__=BaseOutputOptions,
                             _target_cls=PrivateAttr1(target_cls),
                             no_headers=(Optional[bool],
                                         FieldInfo1(False,
                                                    alias='no-headers',
                                                    description='(tabular output) do not display column headers')),
                             **{f'{"include_" if python_attr in disambiguate else ""}{python_attr}':
                                  (bool,
                                   FieldInfo1(False,
                                              alias=python_attr.replace('_', '-') if '_' in python_attr else None,
                                              description=f'(tabular output) include the field {original_attr} in the output',
                                              column=True,
                                              disambiguated=python_attr in disambiguate))
                                for python_attr, original_attr in target_cls.attribute_map.items()})
'''

DEFAULT_INDENT: int = 4


@dataclass(kw_only=True)
class _FormatOpts:
    direct: Optional[bool] = None
    json: Optional[bool] = None
    tabular: Optional[bool] = None
    yaml: Optional[bool] = None
    highlight: Optional[bool] = None
    indent: Optional[int] = None
    jsonpath: Optional[str] = None
    field: Optional[tuple[str, ...]] = None
    header: Optional[bool] = None
    table_format: Optional[TableFormat] = None

    def __post_init__(self):
        if not(any([self.direct, self.json, self.tabular, self.yaml])):
            self.tabular = True
        if self.highlight is None:
            self.highlight = True
        if self.indent is None:
            self.indent = DEFAULT_INDENT
        if self.field is None:
            pass ### FIXME
        if self.header is None:
            self.header = True
        if self.table_format is None:
            self.table_format = TableFormat.ROUNDED_OUTLINE


def make_output_option_group(target_cls: type[SwaggerObject]):
    choices: tuple[str, ...] = tuple(python_attr for python_attr in target_cls.attribute_map.keys())
    return option_group(
        'Output options',
        mutually_exclusive(
            option('--direct', '-d', is_flag=True, help='Output the result directly as a Python object.'),
            option('--json', '-j', is_flag=True, help='Output the result as JSON.'),
            option('--tabular', '-t', is_flag=True, help='Output the result in tabular form. This is the default.'),
            option('--yaml', '-y', is_flag=True, help='Output the result as YAML.'),
        ),
        If(Not(AnySet('direct', 'json', 'yaml')), accept_none)(
            option('--highlight/--no-highlight', is_flag=True, default=None, help='Set whether to use Pygments to highlight the output. Default: --highlight'),
            option('--indent', metavar='N', type=NonNegativeInt, help=f'Set the indentation to N spaces. Default: {DEFAULT_INDENT}'),
            option('--jsonpath', '-J', metavar='EXPR', help='Apply the JSONPath expression EXPR before outputting the result.')
        ),
        If(AnySet('direct', 'json', 'yaml'), accept_none)(
            option('--field', '-f', metavar='FIELD', type=Choice(choices), multiple=True, help=f'Include the field FIELD in tabular output. Default: all fields ({", ".join(choices)})'),
            option('--header/--no-header', is_flag=True, default=None, help='Set whether to include a header row in tabular output. Default: --header'),
            # Had runtime problems if table_format_option was in a constraint (KeyError: 'table_format')
            option('--table-format', '-T', type=EnumChoice(TableFormat, choice_source=ChoiceSource.VALUE), help=f'Set the rendering of tables to the given style. Default: --table-format={TableFormat.ROUNDED_OUTLINE}')
        ),
    )


def display(opts: _FormatOpts,
            iterable_or_obj: Union[Iterable[SwaggerObject], SwaggerObject],
            file: Any = sys.stdout) -> None:
    list_or_obj: Union[list[SwaggerObject], SwaggerObject]
    if isinstance(iterable_or_obj, Iterable):
        list_or_obj = [x.to_dict() for x in iterable_or_obj]
    else:
        list_or_obj = iterable_or_obj.to_dict()

    if opts.tabular:
        raise RuntimeError('Not implemented yet')
    else:
        display_structured(opts, list_or_obj, file=file)


def display_structured(opts: _FormatOpts,
                        list_or_obj: Union[list[SwaggerObject], SwaggerObject],
                        file: Any = sys.stdout) -> None:
    if opts.jsonpath:
        list_or_obj = jsonpath.findall(opts.jsonpath, list_or_obj)

    if opts.direct:
        display_direct(opts, list_or_obj, file=file)
    elif opts.json:
        display_json(opts, list_or_obj, file=file)
    elif opts.yaml:
        display_yaml(opts, list_or_obj, file=file)
    else:
        raise InternalError from ValueError(opts)


def display_direct(opts: _FormatOpts,
                   list_or_obj: Union[list[SwaggerObject], SwaggerObject],
                   file: Any = sys.stdout) -> None:
    target = pformat(list_or_obj, indent=opts.indent)
    echo(highlight(target, PythonLexer(), Terminal256Formatter()) if opts.highlight else target, file=file)


def display_json(opts: _FormatOpts,
                 list_or_obj: Union[list[SwaggerObject], SwaggerObject],
                 file: Any = sys.stdout) -> None:
    target = json.dumps(list_or_obj, indent=opts.indent)
    echo(highlight(target, JsonLexer(), Terminal256Formatter()) if opts.highlight else target, file=file)

# def display_tabular(opts: _FormatOpts,
#                     iterable: Iterable[SwaggerObject],
#                     file: Any = sys.stdout) -> None:
#     attrs = [attr.removeprefix('include_') if model.field_info.extra.get('disambiguated') else attr for attr, model in
#              self.__fields__.items() if model.field_info.extra.get('column') and getattr(self, attr)] \
#             or [attr.removeprefix('include_') if model.field_info.extra.get('disambiguated') else attr for attr, model
#                 in self.__fields__.items() if model.field_info.extra.get('column')]
#     headers = [] if self.no_headers else [self._target_cls.attribute_map[attr] for attr in attrs]
#     data = [[str(getattr(obj, attr)) for attr in attrs] for obj in iterable]
#     print(tabulate.tabulate(data, headers=headers, tablefmt=self.tabular_format), file=file)


def display_yaml(opts: _FormatOpts,
                 list_or_obj: Union[list[SwaggerObject], SwaggerObject],
                 file: Any = sys.stdout) -> None:
    target = yaml.dump(list_or_obj, indent=opts.indent)
    echo(highlight(target, YamlLexer(), Terminal256Formatter()) if opts.highlight else target, file=file)
