#!/usr/bin/env python3

# Copyright (c) 2000-2025, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Remove in Python 3.14
# See https://stackoverflow.com/questions/33533148/how-do-i-type-hint-a-method-with-the-type-of-the-enclosing-class/33533514#33533514
from __future__ import annotations

import json
import jsonpath
import sys
from typing import Any, ClassVar, Optional
import warnings
import yaml

from lockss.pybasic.cliutil import at_most_one
from lockss.pybasic.outpututil import OutputFormat
from pydantic.v1 import BaseModel, PositiveInt, create_model, root_validator, validator
from pydantic.v1.fields import Field, FieldInfo, PrivateAttr
import tabulate


#: The objects generated by Swagger-Codegen
SwaggerObject = object


class BaseOutputOptions(BaseModel):
    DEFAULT_INDENT: ClassVar[PositiveInt] = 4
    DEFAULT_TABULAR: ClassVar[str] = 'tsv'

    x_json: Optional[bool] = Field(False, alias='json', aliases=['-j'], description='(output style) output the result as JSON; default if no output style is specified') # 'json' is a BaseModel name
    jsonpath: Optional[str] = Field(aliases=['-J'], description='(output style) output the result after applying the given JSONPath')
    tabular: Optional[bool] = Field(False, aliases=['-t'], description='(output style) output the result in tabular form')
    yaml: Optional[bool] = Field(False, aliases=['-y'], description='(output style) output the result as YAML')
    indent: Optional[PositiveInt] = Field(DEFAULT_INDENT, description='(JSON/YAML output) indentation spaces')
    tabular_format: Optional[str] = Field(DEFAULT_TABULAR, aliases=['-T'], description=f'(output style) output the result in the given tabular format; choices: {', '.join(OutputFormat.__members__)}')

    @root_validator
    def _validate_output_type(cls: type[BaseOutputOptions], values: dict[str, Any]) -> dict[str, Any]:
        return at_most_one(cls, values, 'x_json', 'jsonpath', 'tabular', 'yaml')

    @validator('tabular_format')
    def _validate_tabular(cls: type[BaseOutputOptions], v: Optional[str]) -> Optional[str]:
        if v and v not in OutputFormat.__members__:
            raise ValueError(f'exactly one of {', '.join(OutputFormat.__members__)} required; got {v}')
        return v

    def display(self, obj: SwaggerObject, file: Any=sys.stdout) -> None:
        if self.jsonpath:
            self.display_jsonpath(obj, file=file)
        elif self.tabular:
            self.display_tabular(obj, file=file)
        elif self.yaml:
            self.display_yaml(obj, file=file)
        else: # x_json is the default
            self.display_json(obj, file=file)

    def display_json(self, obj: SwaggerObject, file: Any) -> None:
        print(json.dumps(obj.to_dict(), indent=self.indent), file=file)

    def display_jsonpath(self, obj: SwaggerObject, file: Any) -> None:
        print(jsonpath.findall(self.jsonpath, obj.to_dict()), file=file)

    def display_tabular(self, obj: SwaggerObject, file: Any) -> None:
        vals = [str(getattr(obj, attr)) for attr in self._target_cls.swagger_types if getattr(self, attr)]
        print(tabulate.tabulate([vals], tablefmt=self.tabular_format), file=file)

    def display_yaml(self, obj: SwaggerObject, file: Any) -> None:
        print(yaml.dump(obj.to_dict(), indent=self.indent), file=file)


def create_output_options(type_name: str, target_cls: type[SwaggerObject]):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore") # Pydantic v1 demands that PrivateAttr begins with a hyphen but warns that _target_cls begins with a hyphen
        return create_model(type_name, __base__=BaseOutputOptions, _target_cls=PrivateAttr(target_cls), **{attr: (Optional[bool], FieldInfo(False, description=f'(tabular output) include the field {attr} in the output')) for attr in target_cls.swagger_types})
