#!/usr/bin/env python3

# Copyright (c) 2000-2025, Board of Trustees of Leland Stanford Jr. University
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Remove in Python 3.14
# See https://stackoverflow.com/questions/33533148/how-do-i-type-hint-a-method-with-the-type-of-the-enclosing-class/33533514#33533514
from __future__ import annotations

from collections.abc import Iterable
import json
import jsonpath
import sys
from typing import Any, ClassVar, Optional, Union
import warnings
import yaml

from click_extra import option, option_group, table_format_option
from cloup.constraints import mutually_exclusive

'''
from lockss.pybasic.cliutil import at_most_one
from lockss.pybasic.outpututil import OutputFormat
from pydantic.v1 import BaseModel as BaseModel1, PositiveInt as PositiveInt1, create_model as create_model1, root_validator as root_validator1, validator as validator1
from pydantic.v1.fields import Field as Field1, FieldInfo as FieldInfo1, PrivateAttr as PrivateAttr1
import tabulate
'''

#: The objects generated by Swagger-Codegen
SwaggerObject = object


'''
class BaseOutputOptions(BaseModel1):
    DEFAULT_INDENT: ClassVar[PositiveInt1] = 4
    DEFAULT_TABULAR: ClassVar[str] = 'tsv'

    x_json: Optional[bool] = Field1(False, alias='json', aliases=['-j'], description='(output style) output the result as JSON') # 'json' is a BaseModel name
    jsonpath: Optional[str] = Field1(aliases=['-J'], description='(output style) output the result after applying the given JSONPath')
    tabular: Optional[bool] = Field1(False, aliases=['-t'], description='(output style) output the result in tabular form')
    yaml: Optional[bool] = Field1(False, aliases=['-y'], description='(output style) output the result as YAML')
    indent: Optional[PositiveInt1] = Field1(DEFAULT_INDENT, description='(JSON/YAML output) indentation spaces')
    tabular_format: Optional[str] = Field1(DEFAULT_TABULAR, aliases=['-T'], description=f'(tabular output) output the result in the given tabular format; choices: {', '.join(OutputFormat.__members__)}')

    @root_validator1
    def _validate_output_type(cls: type[BaseOutputOptions], values: dict[str, Any]) -> dict[str, Any]:
        return at_most_one(cls, values, 'x_json', 'jsonpath', 'tabular', 'yaml')

    @validator1('tabular_format')
    def _validate_tabular(cls: type[BaseOutputOptions], v: Optional[str]) -> Optional[str]:
        if v and v not in OutputFormat.__members__:
            raise ValueError(f'exactly one of {', '.join(OutputFormat.__members__)} required; got {v}')
        return v

    def display(self,
                iterable_or_obj: Union[Iterable[SwaggerObject], SwaggerObject],
                file: Any=sys.stdout) -> None:
        iterable = iterable_or_obj if isinstance(iterable_or_obj, Iterable) else [iterable_or_obj]
        if self.x_json:
            self.display_json(iterable, file=file)
        elif self.jsonpath:
            self.display_jsonpath(iterable, file=file)
        elif self.tabular:
            self.display_tabular(iterable, file=file)
        elif self.yaml:
            self.display_yaml(iterable, file=file)
        else:
            for obj in iterable:
                print(obj.to_dict())

    def display_json(self, iterable: Iterable[SwaggerObject], file: Any) -> None:
        for obj in iterable:
            print(json.dumps(obj.to_dict(), indent=self.indent), file=file)

    def display_jsonpath(self, iterable: Iterable[SwaggerObject], file: Any) -> None:
        for obj in iterable:
            print(jsonpath.findall(self.jsonpath, obj.to_dict()), file=file)

    def display_tabular(self, iterable: Iterable[SwaggerObject], file: Any) -> None:
        attrs = [attr.removeprefix('include_') if model.field_info.extra.get('disambiguated') else attr for attr, model in self.__fields__.items() if model.field_info.extra.get('column') and getattr(self, attr)] \
                or [attr.removeprefix('include_') if model.field_info.extra.get('disambiguated') else attr for attr, model in self.__fields__.items() if model.field_info.extra.get('column')]
        headers = [] if self.no_headers else [self._target_cls.attribute_map[attr] for attr in attrs]
        data = [[str(getattr(obj, attr)) for attr in attrs] for obj in iterable]
        print(tabulate.tabulate(data, headers=headers, tablefmt=self.tabular_format), file=file)

    def display_yaml(self, iterable: Iterable[SwaggerObject], file: Any) -> None:
        for obj in iterable:
            print(yaml.dump(obj.to_dict(), indent=self.indent), file=file)


def output_options(type_name: str,
                   target_cls: type[SwaggerObject],
                   disambiguate: Optional[list[str]] = None):
    disambiguate = disambiguate or []
    with warnings.catch_warnings():
        warnings.simplefilter("ignore") # Pydantic v1 demands that PrivateAttr begins with a hyphen but warns that _target_cls begins with a hyphen
        return create_model1(type_name,
                             __base__=BaseOutputOptions,
                             _target_cls=PrivateAttr1(target_cls),
                             no_headers=(Optional[bool],
                                         FieldInfo1(False,
                                                    alias='no-headers',
                                                    description='(tabular output) do not display column headers')),
                             **{f'{"include_" if python_attr in disambiguate else ""}{python_attr}':
                                  (bool,
                                   FieldInfo1(False,
                                              alias=python_attr.replace('_', '-') if '_' in python_attr else None,
                                              description=f'(tabular output) include the field {original_attr} in the output',
                                              column=True,
                                              disambiguated=python_attr in disambiguate))
                                for python_attr, original_attr in target_cls.attribute_map.items()})
'''

_format_options = option_group(
    'Format options',
    mutually_exclusive(
        option('--json', '-j', is_flag=True, help='Output the result as JSON.'),
        option('--jsonpath', '-J', metavar='EXPR', help='Output the result after applying the JSONPath expression EXPR.'),
        option('--tabular', '-t', is_flag=True, help='Output the result in tabular form. This is the default behavior.'),
        option('--yaml', '-y', is_flag=True, help='Output the result as YAML.')
    ),
    table_format_option('--table-format', '-T', help='Set the rendering of tables to the given style. Ignored unless --tabular is set.')
)
