# coding: utf-8

"""
    LOCKSS Configuration Service REST API

    REST API of the LOCKSS Configuration Service  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuAgreements(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auid': 'str',
        'raw_map': 'dict(str, PeerAgreements)'
    }

    attribute_map = {
        'auid': 'auid',
        'raw_map': 'rawMap'
    }

    def __init__(self, auid=None, raw_map=None):  # noqa: E501
        """AuAgreements - a model defined in Swagger"""  # noqa: E501
        self._auid = None
        self._raw_map = None
        self.discriminator = None
        if auid is not None:
            self.auid = auid
        if raw_map is not None:
            self.raw_map = raw_map

    @property
    def auid(self):
        """Gets the auid of this AuAgreements.  # noqa: E501


        :return: The auid of this AuAgreements.  # noqa: E501
        :rtype: str
        """
        return self._auid

    @auid.setter
    def auid(self, auid):
        """Sets the auid of this AuAgreements.


        :param auid: The auid of this AuAgreements.  # noqa: E501
        :type: str
        """

        self._auid = auid

    @property
    def raw_map(self):
        """Gets the raw_map of this AuAgreements.  # noqa: E501


        :return: The raw_map of this AuAgreements.  # noqa: E501
        :rtype: dict(str, PeerAgreements)
        """
        return self._raw_map

    @raw_map.setter
    def raw_map(self, raw_map):
        """Sets the raw_map of this AuAgreements.


        :param raw_map: The raw_map of this AuAgreements.  # noqa: E501
        :type: dict(str, PeerAgreements)
        """

        self._raw_map = raw_map

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuAgreements, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuAgreements):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
