# coding: utf-8

"""
    LOCKSS Configuration Service REST API

    REST API of the LOCKSS Configuration Service  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuSuspectUrlVersions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auid': 'str',
        'suspect_versions': 'list[list[SuspectUrlVersion]]'
    }

    attribute_map = {
        'auid': 'auid',
        'suspect_versions': 'suspectVersions'
    }

    def __init__(self, auid=None, suspect_versions=None):  # noqa: E501
        """AuSuspectUrlVersions - a model defined in Swagger"""  # noqa: E501
        self._auid = None
        self._suspect_versions = None
        self.discriminator = None
        if auid is not None:
            self.auid = auid
        if suspect_versions is not None:
            self.suspect_versions = suspect_versions

    @property
    def auid(self):
        """Gets the auid of this AuSuspectUrlVersions.  # noqa: E501


        :return: The auid of this AuSuspectUrlVersions.  # noqa: E501
        :rtype: str
        """
        return self._auid

    @auid.setter
    def auid(self, auid):
        """Sets the auid of this AuSuspectUrlVersions.


        :param auid: The auid of this AuSuspectUrlVersions.  # noqa: E501
        :type: str
        """

        self._auid = auid

    @property
    def suspect_versions(self):
        """Gets the suspect_versions of this AuSuspectUrlVersions.  # noqa: E501


        :return: The suspect_versions of this AuSuspectUrlVersions.  # noqa: E501
        :rtype: list[list[SuspectUrlVersion]]
        """
        return self._suspect_versions

    @suspect_versions.setter
    def suspect_versions(self, suspect_versions):
        """Sets the suspect_versions of this AuSuspectUrlVersions.


        :param suspect_versions: The suspect_versions of this AuSuspectUrlVersions.  # noqa: E501
        :type: list[list[SuspectUrlVersion]]
        """

        self._suspect_versions = suspect_versions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuSuspectUrlVersions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuSuspectUrlVersions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
