# coding: utf-8

"""
    LOCKSS Configuration Service REST API

    REST API of the LOCKSS Configuration Service  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuStateBean(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'au_creation_time': 'int',
        'last_crawl_time': 'int',
        'last_crawl_attempt': 'int',
        'last_crawl_result_msg': 'str',
        'last_crawl_result': 'int',
        'last_deep_crawl_time': 'int',
        'last_deep_crawl_attempt': 'int',
        'last_deep_crawl_result_msg': 'str',
        'last_deep_crawl_result': 'int',
        'last_deep_crawl_depth': 'int',
        'last_top_level_poll_time': 'int',
        'last_poll_start': 'int',
        'last_poll_result': 'int',
        'poll_duration': 'int',
        'average_hash_duration': 'int',
        'clockss_subscription_status': 'int',
        'v3_agreement': 'float',
        'highest_v3_agreement': 'float',
        'access_type': 'AccessType',
        'has_substance': 'SubstanceCheckerState',
        'substance_version': 'str',
        'metadata_version': 'str',
        'last_metadata_index': 'int',
        'last_content_change': 'int',
        'last_po_p_poll': 'int',
        'last_po_p_poll_result': 'int',
        'last_local_hash_scan': 'int',
        'num_agree_peers_last_po_r': 'int',
        'num_willing_repairers': 'int',
        'num_current_suspect_versions': 'int',
        'cdn_stems': 'list[str]',
        'is_metadata_extraction_enabled': 'bool',
        'au_id': 'str'
    }

    attribute_map = {
        'au_creation_time': 'auCreationTime',
        'last_crawl_time': 'lastCrawlTime',
        'last_crawl_attempt': 'lastCrawlAttempt',
        'last_crawl_result_msg': 'lastCrawlResultMsg',
        'last_crawl_result': 'lastCrawlResult',
        'last_deep_crawl_time': 'lastDeepCrawlTime',
        'last_deep_crawl_attempt': 'lastDeepCrawlAttempt',
        'last_deep_crawl_result_msg': 'lastDeepCrawlResultMsg',
        'last_deep_crawl_result': 'lastDeepCrawlResult',
        'last_deep_crawl_depth': 'lastDeepCrawlDepth',
        'last_top_level_poll_time': 'lastTopLevelPollTime',
        'last_poll_start': 'lastPollStart',
        'last_poll_result': 'lastPollResult',
        'poll_duration': 'pollDuration',
        'average_hash_duration': 'averageHashDuration',
        'clockss_subscription_status': 'clockssSubscriptionStatus',
        'v3_agreement': 'v3Agreement',
        'highest_v3_agreement': 'highestV3Agreement',
        'access_type': 'accessType',
        'has_substance': 'hasSubstance',
        'substance_version': 'substanceVersion',
        'metadata_version': 'metadataVersion',
        'last_metadata_index': 'lastMetadataIndex',
        'last_content_change': 'lastContentChange',
        'last_po_p_poll': 'lastPoPPoll',
        'last_po_p_poll_result': 'lastPoPPollResult',
        'last_local_hash_scan': 'lastLocalHashScan',
        'num_agree_peers_last_po_r': 'numAgreePeersLastPoR',
        'num_willing_repairers': 'numWillingRepairers',
        'num_current_suspect_versions': 'numCurrentSuspectVersions',
        'cdn_stems': 'cdnStems',
        'is_metadata_extraction_enabled': 'isMetadataExtractionEnabled',
        'au_id': 'auId'
    }

    def __init__(self, au_creation_time=None, last_crawl_time=None, last_crawl_attempt=None, last_crawl_result_msg=None, last_crawl_result=None, last_deep_crawl_time=None, last_deep_crawl_attempt=None, last_deep_crawl_result_msg=None, last_deep_crawl_result=None, last_deep_crawl_depth=None, last_top_level_poll_time=None, last_poll_start=None, last_poll_result=None, poll_duration=None, average_hash_duration=None, clockss_subscription_status=None, v3_agreement=None, highest_v3_agreement=None, access_type=None, has_substance=None, substance_version=None, metadata_version=None, last_metadata_index=None, last_content_change=None, last_po_p_poll=None, last_po_p_poll_result=None, last_local_hash_scan=None, num_agree_peers_last_po_r=None, num_willing_repairers=None, num_current_suspect_versions=None, cdn_stems=None, is_metadata_extraction_enabled=None, au_id=None):  # noqa: E501
        """AuStateBean - a model defined in Swagger"""  # noqa: E501
        self._au_creation_time = None
        self._last_crawl_time = None
        self._last_crawl_attempt = None
        self._last_crawl_result_msg = None
        self._last_crawl_result = None
        self._last_deep_crawl_time = None
        self._last_deep_crawl_attempt = None
        self._last_deep_crawl_result_msg = None
        self._last_deep_crawl_result = None
        self._last_deep_crawl_depth = None
        self._last_top_level_poll_time = None
        self._last_poll_start = None
        self._last_poll_result = None
        self._poll_duration = None
        self._average_hash_duration = None
        self._clockss_subscription_status = None
        self._v3_agreement = None
        self._highest_v3_agreement = None
        self._access_type = None
        self._has_substance = None
        self._substance_version = None
        self._metadata_version = None
        self._last_metadata_index = None
        self._last_content_change = None
        self._last_po_p_poll = None
        self._last_po_p_poll_result = None
        self._last_local_hash_scan = None
        self._num_agree_peers_last_po_r = None
        self._num_willing_repairers = None
        self._num_current_suspect_versions = None
        self._cdn_stems = None
        self._is_metadata_extraction_enabled = None
        self._au_id = None
        self.discriminator = None
        if au_creation_time is not None:
            self.au_creation_time = au_creation_time
        if last_crawl_time is not None:
            self.last_crawl_time = last_crawl_time
        if last_crawl_attempt is not None:
            self.last_crawl_attempt = last_crawl_attempt
        if last_crawl_result_msg is not None:
            self.last_crawl_result_msg = last_crawl_result_msg
        if last_crawl_result is not None:
            self.last_crawl_result = last_crawl_result
        if last_deep_crawl_time is not None:
            self.last_deep_crawl_time = last_deep_crawl_time
        if last_deep_crawl_attempt is not None:
            self.last_deep_crawl_attempt = last_deep_crawl_attempt
        if last_deep_crawl_result_msg is not None:
            self.last_deep_crawl_result_msg = last_deep_crawl_result_msg
        if last_deep_crawl_result is not None:
            self.last_deep_crawl_result = last_deep_crawl_result
        if last_deep_crawl_depth is not None:
            self.last_deep_crawl_depth = last_deep_crawl_depth
        if last_top_level_poll_time is not None:
            self.last_top_level_poll_time = last_top_level_poll_time
        if last_poll_start is not None:
            self.last_poll_start = last_poll_start
        if last_poll_result is not None:
            self.last_poll_result = last_poll_result
        if poll_duration is not None:
            self.poll_duration = poll_duration
        if average_hash_duration is not None:
            self.average_hash_duration = average_hash_duration
        if clockss_subscription_status is not None:
            self.clockss_subscription_status = clockss_subscription_status
        if v3_agreement is not None:
            self.v3_agreement = v3_agreement
        if highest_v3_agreement is not None:
            self.highest_v3_agreement = highest_v3_agreement
        if access_type is not None:
            self.access_type = access_type
        if has_substance is not None:
            self.has_substance = has_substance
        if substance_version is not None:
            self.substance_version = substance_version
        if metadata_version is not None:
            self.metadata_version = metadata_version
        if last_metadata_index is not None:
            self.last_metadata_index = last_metadata_index
        if last_content_change is not None:
            self.last_content_change = last_content_change
        if last_po_p_poll is not None:
            self.last_po_p_poll = last_po_p_poll
        if last_po_p_poll_result is not None:
            self.last_po_p_poll_result = last_po_p_poll_result
        if last_local_hash_scan is not None:
            self.last_local_hash_scan = last_local_hash_scan
        if num_agree_peers_last_po_r is not None:
            self.num_agree_peers_last_po_r = num_agree_peers_last_po_r
        if num_willing_repairers is not None:
            self.num_willing_repairers = num_willing_repairers
        if num_current_suspect_versions is not None:
            self.num_current_suspect_versions = num_current_suspect_versions
        if cdn_stems is not None:
            self.cdn_stems = cdn_stems
        if is_metadata_extraction_enabled is not None:
            self.is_metadata_extraction_enabled = is_metadata_extraction_enabled
        if au_id is not None:
            self.au_id = au_id

    @property
    def au_creation_time(self):
        """Gets the au_creation_time of this AuStateBean.  # noqa: E501


        :return: The au_creation_time of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._au_creation_time

    @au_creation_time.setter
    def au_creation_time(self, au_creation_time):
        """Sets the au_creation_time of this AuStateBean.


        :param au_creation_time: The au_creation_time of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._au_creation_time = au_creation_time

    @property
    def last_crawl_time(self):
        """Gets the last_crawl_time of this AuStateBean.  # noqa: E501


        :return: The last_crawl_time of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_crawl_time

    @last_crawl_time.setter
    def last_crawl_time(self, last_crawl_time):
        """Sets the last_crawl_time of this AuStateBean.


        :param last_crawl_time: The last_crawl_time of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_crawl_time = last_crawl_time

    @property
    def last_crawl_attempt(self):
        """Gets the last_crawl_attempt of this AuStateBean.  # noqa: E501


        :return: The last_crawl_attempt of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_crawl_attempt

    @last_crawl_attempt.setter
    def last_crawl_attempt(self, last_crawl_attempt):
        """Sets the last_crawl_attempt of this AuStateBean.


        :param last_crawl_attempt: The last_crawl_attempt of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_crawl_attempt = last_crawl_attempt

    @property
    def last_crawl_result_msg(self):
        """Gets the last_crawl_result_msg of this AuStateBean.  # noqa: E501


        :return: The last_crawl_result_msg of this AuStateBean.  # noqa: E501
        :rtype: str
        """
        return self._last_crawl_result_msg

    @last_crawl_result_msg.setter
    def last_crawl_result_msg(self, last_crawl_result_msg):
        """Sets the last_crawl_result_msg of this AuStateBean.


        :param last_crawl_result_msg: The last_crawl_result_msg of this AuStateBean.  # noqa: E501
        :type: str
        """

        self._last_crawl_result_msg = last_crawl_result_msg

    @property
    def last_crawl_result(self):
        """Gets the last_crawl_result of this AuStateBean.  # noqa: E501


        :return: The last_crawl_result of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_crawl_result

    @last_crawl_result.setter
    def last_crawl_result(self, last_crawl_result):
        """Sets the last_crawl_result of this AuStateBean.


        :param last_crawl_result: The last_crawl_result of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_crawl_result = last_crawl_result

    @property
    def last_deep_crawl_time(self):
        """Gets the last_deep_crawl_time of this AuStateBean.  # noqa: E501


        :return: The last_deep_crawl_time of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_deep_crawl_time

    @last_deep_crawl_time.setter
    def last_deep_crawl_time(self, last_deep_crawl_time):
        """Sets the last_deep_crawl_time of this AuStateBean.


        :param last_deep_crawl_time: The last_deep_crawl_time of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_deep_crawl_time = last_deep_crawl_time

    @property
    def last_deep_crawl_attempt(self):
        """Gets the last_deep_crawl_attempt of this AuStateBean.  # noqa: E501


        :return: The last_deep_crawl_attempt of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_deep_crawl_attempt

    @last_deep_crawl_attempt.setter
    def last_deep_crawl_attempt(self, last_deep_crawl_attempt):
        """Sets the last_deep_crawl_attempt of this AuStateBean.


        :param last_deep_crawl_attempt: The last_deep_crawl_attempt of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_deep_crawl_attempt = last_deep_crawl_attempt

    @property
    def last_deep_crawl_result_msg(self):
        """Gets the last_deep_crawl_result_msg of this AuStateBean.  # noqa: E501


        :return: The last_deep_crawl_result_msg of this AuStateBean.  # noqa: E501
        :rtype: str
        """
        return self._last_deep_crawl_result_msg

    @last_deep_crawl_result_msg.setter
    def last_deep_crawl_result_msg(self, last_deep_crawl_result_msg):
        """Sets the last_deep_crawl_result_msg of this AuStateBean.


        :param last_deep_crawl_result_msg: The last_deep_crawl_result_msg of this AuStateBean.  # noqa: E501
        :type: str
        """

        self._last_deep_crawl_result_msg = last_deep_crawl_result_msg

    @property
    def last_deep_crawl_result(self):
        """Gets the last_deep_crawl_result of this AuStateBean.  # noqa: E501


        :return: The last_deep_crawl_result of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_deep_crawl_result

    @last_deep_crawl_result.setter
    def last_deep_crawl_result(self, last_deep_crawl_result):
        """Sets the last_deep_crawl_result of this AuStateBean.


        :param last_deep_crawl_result: The last_deep_crawl_result of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_deep_crawl_result = last_deep_crawl_result

    @property
    def last_deep_crawl_depth(self):
        """Gets the last_deep_crawl_depth of this AuStateBean.  # noqa: E501


        :return: The last_deep_crawl_depth of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_deep_crawl_depth

    @last_deep_crawl_depth.setter
    def last_deep_crawl_depth(self, last_deep_crawl_depth):
        """Sets the last_deep_crawl_depth of this AuStateBean.


        :param last_deep_crawl_depth: The last_deep_crawl_depth of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_deep_crawl_depth = last_deep_crawl_depth

    @property
    def last_top_level_poll_time(self):
        """Gets the last_top_level_poll_time of this AuStateBean.  # noqa: E501


        :return: The last_top_level_poll_time of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_top_level_poll_time

    @last_top_level_poll_time.setter
    def last_top_level_poll_time(self, last_top_level_poll_time):
        """Sets the last_top_level_poll_time of this AuStateBean.


        :param last_top_level_poll_time: The last_top_level_poll_time of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_top_level_poll_time = last_top_level_poll_time

    @property
    def last_poll_start(self):
        """Gets the last_poll_start of this AuStateBean.  # noqa: E501


        :return: The last_poll_start of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_poll_start

    @last_poll_start.setter
    def last_poll_start(self, last_poll_start):
        """Sets the last_poll_start of this AuStateBean.


        :param last_poll_start: The last_poll_start of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_poll_start = last_poll_start

    @property
    def last_poll_result(self):
        """Gets the last_poll_result of this AuStateBean.  # noqa: E501


        :return: The last_poll_result of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_poll_result

    @last_poll_result.setter
    def last_poll_result(self, last_poll_result):
        """Sets the last_poll_result of this AuStateBean.


        :param last_poll_result: The last_poll_result of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_poll_result = last_poll_result

    @property
    def poll_duration(self):
        """Gets the poll_duration of this AuStateBean.  # noqa: E501


        :return: The poll_duration of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._poll_duration

    @poll_duration.setter
    def poll_duration(self, poll_duration):
        """Sets the poll_duration of this AuStateBean.


        :param poll_duration: The poll_duration of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._poll_duration = poll_duration

    @property
    def average_hash_duration(self):
        """Gets the average_hash_duration of this AuStateBean.  # noqa: E501


        :return: The average_hash_duration of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._average_hash_duration

    @average_hash_duration.setter
    def average_hash_duration(self, average_hash_duration):
        """Sets the average_hash_duration of this AuStateBean.


        :param average_hash_duration: The average_hash_duration of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._average_hash_duration = average_hash_duration

    @property
    def clockss_subscription_status(self):
        """Gets the clockss_subscription_status of this AuStateBean.  # noqa: E501


        :return: The clockss_subscription_status of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._clockss_subscription_status

    @clockss_subscription_status.setter
    def clockss_subscription_status(self, clockss_subscription_status):
        """Sets the clockss_subscription_status of this AuStateBean.


        :param clockss_subscription_status: The clockss_subscription_status of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._clockss_subscription_status = clockss_subscription_status

    @property
    def v3_agreement(self):
        """Gets the v3_agreement of this AuStateBean.  # noqa: E501


        :return: The v3_agreement of this AuStateBean.  # noqa: E501
        :rtype: float
        """
        return self._v3_agreement

    @v3_agreement.setter
    def v3_agreement(self, v3_agreement):
        """Sets the v3_agreement of this AuStateBean.


        :param v3_agreement: The v3_agreement of this AuStateBean.  # noqa: E501
        :type: float
        """

        self._v3_agreement = v3_agreement

    @property
    def highest_v3_agreement(self):
        """Gets the highest_v3_agreement of this AuStateBean.  # noqa: E501


        :return: The highest_v3_agreement of this AuStateBean.  # noqa: E501
        :rtype: float
        """
        return self._highest_v3_agreement

    @highest_v3_agreement.setter
    def highest_v3_agreement(self, highest_v3_agreement):
        """Sets the highest_v3_agreement of this AuStateBean.


        :param highest_v3_agreement: The highest_v3_agreement of this AuStateBean.  # noqa: E501
        :type: float
        """

        self._highest_v3_agreement = highest_v3_agreement

    @property
    def access_type(self):
        """Gets the access_type of this AuStateBean.  # noqa: E501


        :return: The access_type of this AuStateBean.  # noqa: E501
        :rtype: AccessType
        """
        return self._access_type

    @access_type.setter
    def access_type(self, access_type):
        """Sets the access_type of this AuStateBean.


        :param access_type: The access_type of this AuStateBean.  # noqa: E501
        :type: AccessType
        """

        self._access_type = access_type

    @property
    def has_substance(self):
        """Gets the has_substance of this AuStateBean.  # noqa: E501


        :return: The has_substance of this AuStateBean.  # noqa: E501
        :rtype: SubstanceCheckerState
        """
        return self._has_substance

    @has_substance.setter
    def has_substance(self, has_substance):
        """Sets the has_substance of this AuStateBean.


        :param has_substance: The has_substance of this AuStateBean.  # noqa: E501
        :type: SubstanceCheckerState
        """

        self._has_substance = has_substance

    @property
    def substance_version(self):
        """Gets the substance_version of this AuStateBean.  # noqa: E501


        :return: The substance_version of this AuStateBean.  # noqa: E501
        :rtype: str
        """
        return self._substance_version

    @substance_version.setter
    def substance_version(self, substance_version):
        """Sets the substance_version of this AuStateBean.


        :param substance_version: The substance_version of this AuStateBean.  # noqa: E501
        :type: str
        """

        self._substance_version = substance_version

    @property
    def metadata_version(self):
        """Gets the metadata_version of this AuStateBean.  # noqa: E501


        :return: The metadata_version of this AuStateBean.  # noqa: E501
        :rtype: str
        """
        return self._metadata_version

    @metadata_version.setter
    def metadata_version(self, metadata_version):
        """Sets the metadata_version of this AuStateBean.


        :param metadata_version: The metadata_version of this AuStateBean.  # noqa: E501
        :type: str
        """

        self._metadata_version = metadata_version

    @property
    def last_metadata_index(self):
        """Gets the last_metadata_index of this AuStateBean.  # noqa: E501


        :return: The last_metadata_index of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_metadata_index

    @last_metadata_index.setter
    def last_metadata_index(self, last_metadata_index):
        """Sets the last_metadata_index of this AuStateBean.


        :param last_metadata_index: The last_metadata_index of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_metadata_index = last_metadata_index

    @property
    def last_content_change(self):
        """Gets the last_content_change of this AuStateBean.  # noqa: E501


        :return: The last_content_change of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_content_change

    @last_content_change.setter
    def last_content_change(self, last_content_change):
        """Sets the last_content_change of this AuStateBean.


        :param last_content_change: The last_content_change of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_content_change = last_content_change

    @property
    def last_po_p_poll(self):
        """Gets the last_po_p_poll of this AuStateBean.  # noqa: E501


        :return: The last_po_p_poll of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_po_p_poll

    @last_po_p_poll.setter
    def last_po_p_poll(self, last_po_p_poll):
        """Sets the last_po_p_poll of this AuStateBean.


        :param last_po_p_poll: The last_po_p_poll of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_po_p_poll = last_po_p_poll

    @property
    def last_po_p_poll_result(self):
        """Gets the last_po_p_poll_result of this AuStateBean.  # noqa: E501


        :return: The last_po_p_poll_result of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_po_p_poll_result

    @last_po_p_poll_result.setter
    def last_po_p_poll_result(self, last_po_p_poll_result):
        """Sets the last_po_p_poll_result of this AuStateBean.


        :param last_po_p_poll_result: The last_po_p_poll_result of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_po_p_poll_result = last_po_p_poll_result

    @property
    def last_local_hash_scan(self):
        """Gets the last_local_hash_scan of this AuStateBean.  # noqa: E501


        :return: The last_local_hash_scan of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._last_local_hash_scan

    @last_local_hash_scan.setter
    def last_local_hash_scan(self, last_local_hash_scan):
        """Sets the last_local_hash_scan of this AuStateBean.


        :param last_local_hash_scan: The last_local_hash_scan of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._last_local_hash_scan = last_local_hash_scan

    @property
    def num_agree_peers_last_po_r(self):
        """Gets the num_agree_peers_last_po_r of this AuStateBean.  # noqa: E501


        :return: The num_agree_peers_last_po_r of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._num_agree_peers_last_po_r

    @num_agree_peers_last_po_r.setter
    def num_agree_peers_last_po_r(self, num_agree_peers_last_po_r):
        """Sets the num_agree_peers_last_po_r of this AuStateBean.


        :param num_agree_peers_last_po_r: The num_agree_peers_last_po_r of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._num_agree_peers_last_po_r = num_agree_peers_last_po_r

    @property
    def num_willing_repairers(self):
        """Gets the num_willing_repairers of this AuStateBean.  # noqa: E501


        :return: The num_willing_repairers of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._num_willing_repairers

    @num_willing_repairers.setter
    def num_willing_repairers(self, num_willing_repairers):
        """Sets the num_willing_repairers of this AuStateBean.


        :param num_willing_repairers: The num_willing_repairers of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._num_willing_repairers = num_willing_repairers

    @property
    def num_current_suspect_versions(self):
        """Gets the num_current_suspect_versions of this AuStateBean.  # noqa: E501


        :return: The num_current_suspect_versions of this AuStateBean.  # noqa: E501
        :rtype: int
        """
        return self._num_current_suspect_versions

    @num_current_suspect_versions.setter
    def num_current_suspect_versions(self, num_current_suspect_versions):
        """Sets the num_current_suspect_versions of this AuStateBean.


        :param num_current_suspect_versions: The num_current_suspect_versions of this AuStateBean.  # noqa: E501
        :type: int
        """

        self._num_current_suspect_versions = num_current_suspect_versions

    @property
    def cdn_stems(self):
        """Gets the cdn_stems of this AuStateBean.  # noqa: E501


        :return: The cdn_stems of this AuStateBean.  # noqa: E501
        :rtype: list[str]
        """
        return self._cdn_stems

    @cdn_stems.setter
    def cdn_stems(self, cdn_stems):
        """Sets the cdn_stems of this AuStateBean.


        :param cdn_stems: The cdn_stems of this AuStateBean.  # noqa: E501
        :type: list[str]
        """

        self._cdn_stems = cdn_stems

    @property
    def is_metadata_extraction_enabled(self):
        """Gets the is_metadata_extraction_enabled of this AuStateBean.  # noqa: E501


        :return: The is_metadata_extraction_enabled of this AuStateBean.  # noqa: E501
        :rtype: bool
        """
        return self._is_metadata_extraction_enabled

    @is_metadata_extraction_enabled.setter
    def is_metadata_extraction_enabled(self, is_metadata_extraction_enabled):
        """Sets the is_metadata_extraction_enabled of this AuStateBean.


        :param is_metadata_extraction_enabled: The is_metadata_extraction_enabled of this AuStateBean.  # noqa: E501
        :type: bool
        """

        self._is_metadata_extraction_enabled = is_metadata_extraction_enabled

    @property
    def au_id(self):
        """Gets the au_id of this AuStateBean.  # noqa: E501


        :return: The au_id of this AuStateBean.  # noqa: E501
        :rtype: str
        """
        return self._au_id

    @au_id.setter
    def au_id(self, au_id):
        """Sets the au_id of this AuStateBean.


        :param au_id: The au_id of this AuStateBean.  # noqa: E501
        :type: str
        """

        self._au_id = au_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuStateBean, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuStateBean):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
