# coding: utf-8

"""
    LOCKSS Configuration Service REST API

    REST API of the LOCKSS Configuration Service  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PeerAgreement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'percent_agreement': 'float',
        'percent_agreement_time': 'int',
        'highest_percent_agreement': 'float',
        'highest_percent_agreement_time': 'int'
    }

    attribute_map = {
        'percent_agreement': 'percentAgreement',
        'percent_agreement_time': 'percentAgreementTime',
        'highest_percent_agreement': 'highestPercentAgreement',
        'highest_percent_agreement_time': 'highestPercentAgreementTime'
    }

    def __init__(self, percent_agreement=None, percent_agreement_time=None, highest_percent_agreement=None, highest_percent_agreement_time=None):  # noqa: E501
        """PeerAgreement - a model defined in Swagger"""  # noqa: E501
        self._percent_agreement = None
        self._percent_agreement_time = None
        self._highest_percent_agreement = None
        self._highest_percent_agreement_time = None
        self.discriminator = None
        if percent_agreement is not None:
            self.percent_agreement = percent_agreement
        if percent_agreement_time is not None:
            self.percent_agreement_time = percent_agreement_time
        if highest_percent_agreement is not None:
            self.highest_percent_agreement = highest_percent_agreement
        if highest_percent_agreement_time is not None:
            self.highest_percent_agreement_time = highest_percent_agreement_time

    @property
    def percent_agreement(self):
        """Gets the percent_agreement of this PeerAgreement.  # noqa: E501


        :return: The percent_agreement of this PeerAgreement.  # noqa: E501
        :rtype: float
        """
        return self._percent_agreement

    @percent_agreement.setter
    def percent_agreement(self, percent_agreement):
        """Sets the percent_agreement of this PeerAgreement.


        :param percent_agreement: The percent_agreement of this PeerAgreement.  # noqa: E501
        :type: float
        """

        self._percent_agreement = percent_agreement

    @property
    def percent_agreement_time(self):
        """Gets the percent_agreement_time of this PeerAgreement.  # noqa: E501


        :return: The percent_agreement_time of this PeerAgreement.  # noqa: E501
        :rtype: int
        """
        return self._percent_agreement_time

    @percent_agreement_time.setter
    def percent_agreement_time(self, percent_agreement_time):
        """Sets the percent_agreement_time of this PeerAgreement.


        :param percent_agreement_time: The percent_agreement_time of this PeerAgreement.  # noqa: E501
        :type: int
        """

        self._percent_agreement_time = percent_agreement_time

    @property
    def highest_percent_agreement(self):
        """Gets the highest_percent_agreement of this PeerAgreement.  # noqa: E501


        :return: The highest_percent_agreement of this PeerAgreement.  # noqa: E501
        :rtype: float
        """
        return self._highest_percent_agreement

    @highest_percent_agreement.setter
    def highest_percent_agreement(self, highest_percent_agreement):
        """Sets the highest_percent_agreement of this PeerAgreement.


        :param highest_percent_agreement: The highest_percent_agreement of this PeerAgreement.  # noqa: E501
        :type: float
        """

        self._highest_percent_agreement = highest_percent_agreement

    @property
    def highest_percent_agreement_time(self):
        """Gets the highest_percent_agreement_time of this PeerAgreement.  # noqa: E501


        :return: The highest_percent_agreement_time of this PeerAgreement.  # noqa: E501
        :rtype: int
        """
        return self._highest_percent_agreement_time

    @highest_percent_agreement_time.setter
    def highest_percent_agreement_time(self, highest_percent_agreement_time):
        """Sets the highest_percent_agreement_time of this PeerAgreement.


        :param highest_percent_agreement_time: The highest_percent_agreement_time of this PeerAgreement.  # noqa: E501
        :type: int
        """

        self._highest_percent_agreement_time = highest_percent_agreement_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PeerAgreement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PeerAgreement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
