# coding: utf-8

"""
    LOCKSS Configuration Service REST API

    REST API of the LOCKSS Configuration Service  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PeerAgreements(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'map': 'dict(str, PeerAgreement)'
    }

    attribute_map = {
        'id': 'id',
        'map': 'map'
    }

    def __init__(self, id=None, map=None):  # noqa: E501
        """PeerAgreements - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._map = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if map is not None:
            self.map = map

    @property
    def id(self):
        """Gets the id of this PeerAgreements.  # noqa: E501


        :return: The id of this PeerAgreements.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PeerAgreements.


        :param id: The id of this PeerAgreements.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def map(self):
        """Gets the map of this PeerAgreements.  # noqa: E501


        :return: The map of this PeerAgreements.  # noqa: E501
        :rtype: dict(str, PeerAgreement)
        """
        return self._map

    @map.setter
    def map(self, map):
        """Sets the map of this PeerAgreements.


        :param map: The map of this PeerAgreements.  # noqa: E501
        :type: dict(str, PeerAgreement)
        """

        self._map = map

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PeerAgreements, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PeerAgreements):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
