# coding: utf-8

"""
    LOCKSS Repository Service REST API

    REST API of the LOCKSS Repository Service  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StorageInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'name': 'str',
        'path': 'str',
        'components': 'list[StorageInfo]',
        'size_kb': 'int',
        'used_kb': 'int',
        'avail_kb': 'int',
        'percent_used': 'float',
        'percent_used_string': 'str'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'path': 'path',
        'components': 'components',
        'size_kb': 'sizeKB',
        'used_kb': 'usedKB',
        'avail_kb': 'availKB',
        'percent_used': 'percentUsed',
        'percent_used_string': 'percentUsedString'
    }

    def __init__(self, type=None, name=None, path=None, components=None, size_kb=None, used_kb=None, avail_kb=None, percent_used=None, percent_used_string=None):  # noqa: E501
        """StorageInfo - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._name = None
        self._path = None
        self._components = None
        self._size_kb = None
        self._used_kb = None
        self._avail_kb = None
        self._percent_used = None
        self._percent_used_string = None
        self.discriminator = None
        self.type = type
        self.name = name
        self.path = path
        self.components = components
        self.size_kb = size_kb
        self.used_kb = used_kb
        self.avail_kb = avail_kb
        self.percent_used = percent_used
        self.percent_used_string = percent_used_string

    @property
    def type(self):
        """Gets the type of this StorageInfo.  # noqa: E501

        Type of the storage area  # noqa: E501

        :return: The type of this StorageInfo.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this StorageInfo.

        Type of the storage area  # noqa: E501

        :param type: The type of this StorageInfo.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def name(self):
        """Gets the name of this StorageInfo.  # noqa: E501

        Name of the storage area  # noqa: E501

        :return: The name of this StorageInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this StorageInfo.

        Name of the storage area  # noqa: E501

        :param name: The name of this StorageInfo.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def path(self):
        """Gets the path of this StorageInfo.  # noqa: E501

        Path, if applicable  # noqa: E501

        :return: The path of this StorageInfo.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this StorageInfo.

        Path, if applicable  # noqa: E501

        :param path: The path of this StorageInfo.  # noqa: E501
        :type: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def components(self):
        """Gets the components of this StorageInfo.  # noqa: E501

        Storage areas that comprise this one  # noqa: E501

        :return: The components of this StorageInfo.  # noqa: E501
        :rtype: list[StorageInfo]
        """
        return self._components

    @components.setter
    def components(self, components):
        """Sets the components of this StorageInfo.

        Storage areas that comprise this one  # noqa: E501

        :param components: The components of this StorageInfo.  # noqa: E501
        :type: list[StorageInfo]
        """
        if components is None:
            raise ValueError("Invalid value for `components`, must not be `None`")  # noqa: E501

        self._components = components

    @property
    def size_kb(self):
        """Gets the size_kb of this StorageInfo.  # noqa: E501

        Size of the storage area (in KB)  # noqa: E501

        :return: The size_kb of this StorageInfo.  # noqa: E501
        :rtype: int
        """
        return self._size_kb

    @size_kb.setter
    def size_kb(self, size_kb):
        """Sets the size_kb of this StorageInfo.

        Size of the storage area (in KB)  # noqa: E501

        :param size_kb: The size_kb of this StorageInfo.  # noqa: E501
        :type: int
        """
        if size_kb is None:
            raise ValueError("Invalid value for `size_kb`, must not be `None`")  # noqa: E501

        self._size_kb = size_kb

    @property
    def used_kb(self):
        """Gets the used_kb of this StorageInfo.  # noqa: E501

        Size of the used storage area (in KB)  # noqa: E501

        :return: The used_kb of this StorageInfo.  # noqa: E501
        :rtype: int
        """
        return self._used_kb

    @used_kb.setter
    def used_kb(self, used_kb):
        """Sets the used_kb of this StorageInfo.

        Size of the used storage area (in KB)  # noqa: E501

        :param used_kb: The used_kb of this StorageInfo.  # noqa: E501
        :type: int
        """
        if used_kb is None:
            raise ValueError("Invalid value for `used_kb`, must not be `None`")  # noqa: E501

        self._used_kb = used_kb

    @property
    def avail_kb(self):
        """Gets the avail_kb of this StorageInfo.  # noqa: E501

        Size of the available storage area (in KB)  # noqa: E501

        :return: The avail_kb of this StorageInfo.  # noqa: E501
        :rtype: int
        """
        return self._avail_kb

    @avail_kb.setter
    def avail_kb(self, avail_kb):
        """Sets the avail_kb of this StorageInfo.

        Size of the available storage area (in KB)  # noqa: E501

        :param avail_kb: The avail_kb of this StorageInfo.  # noqa: E501
        :type: int
        """
        if avail_kb is None:
            raise ValueError("Invalid value for `avail_kb`, must not be `None`")  # noqa: E501

        self._avail_kb = avail_kb

    @property
    def percent_used(self):
        """Gets the percent_used of this StorageInfo.  # noqa: E501

        Percentage of the storage area used  # noqa: E501

        :return: The percent_used of this StorageInfo.  # noqa: E501
        :rtype: float
        """
        return self._percent_used

    @percent_used.setter
    def percent_used(self, percent_used):
        """Sets the percent_used of this StorageInfo.

        Percentage of the storage area used  # noqa: E501

        :param percent_used: The percent_used of this StorageInfo.  # noqa: E501
        :type: float
        """
        if percent_used is None:
            raise ValueError("Invalid value for `percent_used`, must not be `None`")  # noqa: E501

        self._percent_used = percent_used

    @property
    def percent_used_string(self):
        """Gets the percent_used_string of this StorageInfo.  # noqa: E501

        Percentage of the storage area used, formatted as a string  # noqa: E501

        :return: The percent_used_string of this StorageInfo.  # noqa: E501
        :rtype: str
        """
        return self._percent_used_string

    @percent_used_string.setter
    def percent_used_string(self, percent_used_string):
        """Sets the percent_used_string of this StorageInfo.

        Percentage of the storage area used, formatted as a string  # noqa: E501

        :param percent_used_string: The percent_used_string of this StorageInfo.  # noqa: E501
        :type: str
        """
        if percent_used_string is None:
            raise ValueError("Invalid value for `percent_used_string`, must not be `None`")  # noqa: E501

        self._percent_used_string = percent_used_string

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StorageInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StorageInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
